server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel_test?serverTimezone=GMT%2b8
  redis:
    host: 192.168.131.129 # redis的ip地址
  jackson:
    time-zone: GMT+08:00
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false

aliyun:
  oss:
    access-key-id: your access-key-id
    access-key-secret: your access-key-secret
    bucket-domain: your bucket-domain
    bucket-name: your bucket-name
    end-point: your end-point


mybatis:
  mapper-locations: classpath:/mapper/*.xml

#MyBatis使用pageHelper分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
